CREATE TABLE [dbo].[Customer]
(
	[Id] INT IDENTITY NOT NULL PRIMARY KEY,
	Name VARCHAR(255) NOT NULL,
	Balance DECIMAL(18, 2) NOT NULL,
	LastUpdated DATETIME2 NOT NULL,
	CreatedOn DATETIME2 NOT NULL,
	RowVersion TIMESTAMP
)
